### ISSUE TITLE
Combining report fails due to breaking changes in Mochawesome merge

### ISSUE THREAD

**Issue by zac11** [bushralam/Cypress#1]
Combining reports fails if the latest version of `mochawesome-merge` is installed. The latest version v4.0 has breaking changes due to which `--reportDir` option is not longer valid and would cause the code to error out.

In your `package.json`, change this

> "combine-reports": "mochawesome-merge --reportDir cypress/reports/mocha > cypress/reports/mochareports/report.json",

to

> "combine-reports": "mochawesome-merge cypress/reports/mocha/mochawesome*.json > cypress/reports/mochareports/report.json",

For reference- [Link](https://github.com/Antontelesh/mochawesome-merge#cli-1)

**Comment by bushralam** [comment]
Thanks zac..
The code has been updated.
